# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31b73ce455d2fc07cc9f14af4276d09facf595c026e673956b370c01c75ecbca0f1a78d7062a308514f52244409d1dacc7cd5f9a5f98e01e420fbd1628e5934d

test:
  secret_key_base: 1a7f2d49787d01792ae6b2975f1f81b368cfd522136f4695e0d60ef3004bc305f7a98240cf485ae4a7a96764ff36fe7008902d6003faf1e2afcb7fa62331bde7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
